version: '2'
services:
  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    environment:
      #  REGISTRY_HTTP_TLS_CERTIFICATE: file:./docker-registry/certs/domain.crt
      #  REGISTRY_HTTP_TLS_KEY: file:./docker-registry/certs/domain.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: file:./docker-registry/auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - ./docker-registry/data:/var/lib/registry
      - ./docker-registry/certs:/certs
      - ./docker-registry/auth:/auth
